# This file was generated by @liquid-labs/catalyst-builder-node. Refer to
# https://npmjs.com/package/@liquid-labs/catalyst-builder-node for further details

#####
# build dist/catalyst-lib-badges.js
#####

CATALYST_CATALYST_LIB_BADGES_JS:=$(DIST)/catalyst-lib-badges.js
CATALYST_CATALYST_LIB_BADGES_JS_ENTRY=$(SRC)/index.mjs
BUILD_TARGETS+=$(CATALYST_CATALYST_LIB_BADGES_JS)

$(CATALYST_CATALYST_LIB_BADGES_JS): package.json $(CATALYST_ALL_NON_TEST_JS_FILES_SRC)
	JS_BUILD_TARGET=$(CATALYST_CATALYST_LIB_BADGES_JS_ENTRY) \
	  JS_OUT=$@ \
	  $(CATALYST_ROLLUP) --config $(CATALYST_ROLLUP_CONFIG)

#####
# end dist/catalyst-lib-badges.js
#####
