# This file was generated by @liquid-labs/sdlc-projects-workflow-node-build. Refer
# to https://npmjs.com/package/@liquid-labs/sdlc-projects-workflow-node-build for
# further details

#####
# build dist/sdlc-lib-badges.js
#####

SDLC_SDLC_LIB_BADGES_JS:=$(DIST)/sdlc-lib-badges.js
SDLC_SDLC_LIB_BADGES_JS_ENTRY=$(SRC)/index.mjs
BUILD_TARGETS+=$(SDLC_SDLC_LIB_BADGES_JS)

$(SDLC_SDLC_LIB_BADGES_JS): package.json $(SDLC_ALL_NON_TEST_JS_FILES_SRC)
	JS_BUILD_TARGET=$(SDLC_SDLC_LIB_BADGES_JS_ENTRY) \
	  JS_OUT=$@ \
	  $(SDLC_ROLLUP) --config $(SDLC_ROLLUP_CONFIG)

#####
# end dist/sdlc-lib-badges.js
#####
